```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)
library(ggplot2)
library(stringr)
```

```{r}
notes <- read_tsv("filtered_data/filtered_notes.tsv")
ratings <- read_tsv("filtered_data/complete_filtered_ratings.tsv")
View(head(notes, 200))
View(head(ratings, 200))
```

#Figure 2
```{r}
notes$trustworthySources <- factor(notes$trustworthySources, levels = c(0, 1), labels = c("Trustworthy sources", "No trustworthy"))

ggplot(notes, aes(x = classification, fill = trustworthySources)) +
    geom_bar() +
    scale_x_discrete(labels = c(
        "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
        "NOT_MISLEADING" = "Not Misleading"
    )) +
    coord_flip()
```

#Figure 3
```{r graph}
misleading_counts <- notes %>%
    summarise(
        misleadingOther = sum(misleadingOther),
        misleadingOutdatedInformation = sum(misleadingOutdatedInformation),
        misleadingFactualError = sum(misleadingFactualError),
        misleadingManipulatedMedia = sum(misleadingManipulatedMedia),
        misleadingMissingImportantContext = sum(misleadingMissingImportantContext),
        misleadingUnverifiedClaimAsFact = sum(misleadingUnverifiedClaimAsFact),
        misleadingSatire = sum(misleadingSatire)
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

ggplot(misleading_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "red") +
    coord_flip() +
    scale_x_discrete(labels = c(
        "misleadingOther" = "Other",
        "misleadingOutdatedInformation" = "Outdated information",
        "misleadingFactualError" = "Factual error",
        "misleadingManipulatedMedia" = "Manipulated media",
        "misleadingMissingImportantContext" = "Missing importamt context",
        "misleadingUnverifiedClaimAsFact" = "Unverified claim as fact",
        "misleadingSatire" = "Satire"
    ))
```

#Figure 4.
```{r graph}
misleading_counts <- notes %>%
    summarise(
        notMisleadingPersonalOpinion = sum(notMisleadingPersonalOpinion),
        notMisleadingOther = sum(notMisleadingOther),
        notMisleadingClearlySatire = sum(notMisleadingClearlySatire),
        notMisleadingFactuallyCorrect = sum(notMisleadingFactuallyCorrect),
        notMisleadingOutdatedButNotWhenWritten = sum(notMisleadingOutdatedButNotWhenWritten),
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

ggplot(misleading_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "blue") +
    coord_flip() +
    labs(y = "Number of Birdwatches notes") +
    scale_x_discrete(labels = c(
        "notMisleadingOther" = "Other",
        "notMisleadingOutdatedButNotWhenWritten" = "Outdated but not when written",
        "notMisleadingPersonalOpinion" = "Personal opinion",
        "notMisleadingFactuallyCorrect" = "Factually correct",
        "notMisleadingClearlySatire" = "Clearly satire"
    ))
```

#Figure 5c.
```{r compute ccdf}
notes <- mutate(notes, word_count = str_count(summary, "\\w+"))

notes <- arrange(notes, word_count)
count_of_distinct <- group_by(notes, classification, word_count) |>
    summarize(count = n()) |>
    group_by(classification) |>
    arrange(classification, word_count) |>
    mutate(notes_with_count = rev(cumsum(rev(count))), total_notes = sum(count), percent = (notes_with_count / total_notes) * 100)

ggplot(count_of_distinct, aes(x = word_count, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = scales::comma) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not Misleading"
        )
    ) +
    labs(
        x = "Word count",
        y = "CCDF (%)",
        title = "CCDF of Word Count by Misleading Status",
        color = "Classification"
    )
```


#Figure 7a.
```{r compute ccdf}
ratings <- group_by(ratings, noteId) |> mutate(votecount = n())

notes$votecount <- ratings$votecount[match(notes$noteId, ratings$noteId)]
# we assumed NA = 0 bc it won't have any row from the ratings table
notes$votecount[is.na(notes$votecount)] <- 0
ratings <- group_by(ratings, noteId) |> mutate(helpful_ratio = sum(helpful) / votecount)

notes$helpful_ratio <- ratings$helpful_ratio[match(notes$noteId, ratings$noteId)]
# we assumed NA = 0 bc it won't have any row from the ratings table
notes$helpful_ratio[is.na(notes$helpful_ratio)] <- 0

helpful_ratio <- group_by(notes, classification, helpful_ratio) |>
    summarize(count = n()) |>
    group_by(classification) |>
    arrange(classification, helpful_ratio) |>
    mutate(helpful = rev(cumsum(rev(count))), total_notes = sum(count), percent = (helpful / total_notes) * 100)

ggplot(helpful_ratio, aes(x = helpful_ratio, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10() +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not Misleading"
        )
    ) +
    labs(
        x = "Helpful Ratios",
        y = "CCDF (%)",
        title = "Helpfulness ratio",
        color = "Classification"
    )
```

#Figure 7b.
```{r compute ccdf}
count_of_votes <- group_by(notes, classification, votecount) |>
    summarize(count = n()) |>
    group_by(classification) |>
    arrange(classification, votecount) |>
    mutate(votes = rev(cumsum(rev(count))), total_notes = sum(count), percent = (votes / total_notes) * 100)
ggplot(count_of_votes, aes(x = votecount, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = scales::comma) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not Misleading"
        )
    ) +
    labs(
        x = "Votes (helpful & not helpful)",
        y = "CCDF (%)",
        title = "Total Votes",
        color = "Classification"
    )
```

#Figure 8.
```{r}
ratings <- read_tsv("filtered_data/complete_filtered_ratings.tsv")
helpful_ratings_counts <- ratings %>%
    summarise(
        helpfulInformative = sum(helpfulInformative),
        helpfulClear = sum(helpfulClear),
        helpfulGoodSources = sum(helpfulGoodSources),
        helpfulEmpathetic = sum(helpfulEmpathetic),
        helpfulUniqueContext = sum(helpfulUniqueContext),
        helpfulAddressesClaim = sum(helpfulAddressesClaim),
        helpfulImportantContext = sum(helpfulImportantContext),
        helpfulOther = sum(helpfulOther)
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

View(helpful_ratings_counts)

ggplot(helpful_ratings_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "navyblue") +
    coord_flip() +
    scale_x_discrete(labels = c(
        "helpfulInformative" = "Informative",
        "helpfulClear" = "Clear",
        "helpfulGoodSources" = "Good sources",
        "helpfulEmpathetic" = "Emphatetic",
        "helpfulUniqueContext" = "Unique context",
        "helpfulAddressesClaim" = "Addresses claim",
        "helpfulImportantContext" = "Important context",
        "helpfulOther" = "Other"
    ))
```


#Figure 9
```{r}
unhelpful_ratings_counts <- ratings %>%
    summarise(
        notHelpfulSourcesMissingOrUnreliable = sum(notHelpfulSourcesMissingOrUnreliable),
        notHelpfulOpinionSpeculationOrBias = sum(notHelpfulOpinionSpeculationOrBias),
        notHelpfulMissingKeyPoints = sum(notHelpfulMissingKeyPoints),
        notHelpfulArgumentativeOrBiased = sum(notHelpfulArgumentativeOrBiased),
        notHelpfulIncorrect = sum(notHelpfulIncorrect),
        notHelpfulOffTopic = sum(notHelpfulOffTopic),
        notHelpfulHardToUnderstand = sum(notHelpfulHardToUnderstand),
        notHelpfulSpamHarassmentOrAbuse = sum(notHelpfulSpamHarassmentOrAbuse),
        notHelpfulOutdated = sum(notHelpfulOutdated),
        notHelpfulIrrelevantSources = sum(notHelpfulIrrelevantSources)
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))
unhelpful_ratings_counts

ggplot(unhelpful_ratings_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "dark red") +
    coord_flip() +
    scale_x_discrete(labels = c(
        notHelpfulSourcesMissingOrUnreliable = ("Sources missing or unreliable"),
        notHelpfulOpinionSpeculationOrBias = ("Opinion speculation or bias"),
        notHelpfulMissingKeyPoints = ("Missing key points"),
        notHelpfulArgumentativeOrBiased = ("Argumentative or inflammatory"),
        notHelpfulIncorrect = ("Incorrect"),
        notHelpfulOffTopic = ("Off topic"),
        notHelpfulHardToUnderstand = ("Hard to understand"),
        notHelpfulSpamHarassmentOrAbuse = ("Spam harassment or abuse"),
        notHelpfulOutdated = ("Outdated"),
        notHelpfulIrrelevantSources = ("Irrevalent sources")
    ))
```

