```{bash}
# donwloaded file in browser bc didn't work to curl here (downloaded as empty)
load(file.path("C:/Users/ds3/Downloads/source_tweets.Rdata"), ournew_env <- new.env())
source_tweets <- ournew_env[["."]]
source_tweets |> head()
```

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)
library(ggplot2)
library(stringr)
library(broom)
```
```{r}
notes <- read_tsv("filtered_data/filtered_notes.tsv")
ratings <- read_tsv("filtered_data/complete_filtered_ratings.tsv")
```

```{r}
notes_with_ratings <- inner_join(notes, ratings, by = "noteId")
notes_ratings_source <- inner_join(notes_with_ratings, source_tweets, by = c("noteId", "tweetId"))
View(head(notes_ratings_source, 200))

# mutate so helpfulnessLevel doesn't intefere
notes_ratings_source <- mutate(notes_ratings_source,
    helpful = if_else(!is.na(helpfulnessLevel) &
        helpfulnessLevel %in% c("HELPFUL", "SOMEWHAT_HELPFUL"), 1, helpful),
    notHelpful = if_else(!is.na(helpfulnessLevel) & helpfulnessLevel == "NOT_HELPFUL",
        1, notHelpful
    )
)

# mutate so we add accountAge
current_date <- Sys.Date()
current_year <- format(current_date, "%Y")

notes_ratings_source <- notes_ratings_source |>
    mutate(account_age = as.numeric(current_year) - as.numeric(year(notes_ratings_source$source_account_created_at)))

notes_ratings_source <- notes_ratings_source %>%
    filter(
        !is.na(helpful),
        !is.na(classification),
        !is.na(trustworthySources),
        !is.na(word_count),
        !is.na(account_age),
        !is.na(source_followers_count),
        !is.na(source_friends_count),
        !is.na(source_verified)
    )

helpful_model <- glm(
    helpful ~ classification + trustworthySources + word_count + account_age +
        source_followers_count + source_friends_count + source_verified,
    family = "binomial",
    data = notes_ratings_source
)

notes_ratings_source <- notes_ratings_source %>%
    mutate(predicted_prob = predict(helpful_model, type = "response"))

predictors <- notes_ratings_source %>% select(word_count, account_age, source_followers_count, source_friends_count)
outcome <- notes_ratings_source$helpful


predictors_scaled <- as_tibble(scale(predictors))

notes_scaled <- bind_cols(predictors_scaled,
    classification = notes_ratings_source$classification,
    trustworthySources = notes_ratings_source$trustworthySources,
    source_verified = notes_ratings_source$source_verified,
    helpful = outcome
)

notes_scaled$classification <- relevel(factor(notes_scaled$classification), ref = "NOT_MISLEADING")
notes_scaled$trustworthySources <- as.factor(notes_scaled$trustworthySources)

helpful_model <- glm(helpful ~ classification + trustworthySources + word_count + account_age + source_followers_count + source_friends_count + source_verified,
    data = notes_scaled, family = "binomial"
)


coef <- tidy(helpful_model)
coef <- coef %>% filter(term != "(Intercept)")

coef$term <- factor(coef$term, levels = c(
    "classificationMISINFORMED_OR_POTENTIALLY_MISLEADING",
    "trustworthySourcesNo trustworthy",
    "word_count",
    "account_age",
    "source_followers_count",
    "source_friends_count",
    "source_verifiedTRUE"
))

ggplot(coef, aes(x = term, y = estimate)) +
    geom_point(size = 8, color = "sea green") +
    geom_errorbar(aes(ymin = estimate - (std.error * 2.56), ymax = estimate + (std.error * 2.56)), width = 0.2, color = "sea green", size = 1.5) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 13)) +
    labs(x = NULL, y = NULL) +
    geom_vline(xintercept = c(2.5, 3.5), linetype = "dashed", color = "black") +
    annotate("text", x = 1, y = 0.95, label = "User categorization", size = 4, fontface = "bold") +
    annotate("text", x = 3, y = 0.95, label = "Text explanation", size = 4, fontface = "bold") +
    annotate("text", x = 4, y = 0.95, label = "Source tweet", size = 4, fontface = "bold") +
    scale_x_discrete(labels = c(
        "account_age" = "Account age",
        "classificationMISINFORMED_OR_POTENTIALLY_MISLEADING" = " Misleading",
        "source_followers_count" = "Followers",
        "source_friends_count" = "Followees",
        "source_verifiedTRUE" = "Verified",
        "trustworthySourcesNo trustworthy" = "Trustworthy Sources",
        "word_count" = "Word count"
    ))
```

```{r}
notes_with_ratings <- inner_join(notes, ratings, by = "noteId")
notes_ratings_source <- inner_join(notes_with_ratings, source_tweets, by = c("noteId", "tweetId"))

# mutate so helpfulnessLevel doesn't intefere
notes_ratings_source <- mutate(notes_ratings_source,
    helpful = if_else(!is.na(helpfulnessLevel) &
        helpfulnessLevel %in% c("HELPFUL", "SOMEWHAT_HELPFUL"), 1, helpful),
    notHelpful = if_else(!is.na(helpfulnessLevel) & helpfulnessLevel == "NOT_HELPFUL",
        1, notHelpful
    )
)

# mutate so we add accountAge
current_date <- Sys.Date()
current_year <- format(current_date, "%Y")

notes_ratings_source <- notes_ratings_source |> mutate(
    account_age = as.numeric(current_year) - as.numeric(year(notes_ratings_source$source_account_created_at))
)

notes_ratings_source <- notes_ratings_source %>%
    filter(
        !is.na(helpful),
        !is.na(classification),
        !is.na(trustworthySources),
        !is.na(word_count),
        !is.na(account_age),
        !is.na(source_followers_count),
        !is.na(source_friends_count),
        !is.na(source_verified)
    )

helpful_model <- glm(
    helpful ~ classification + trustworthySources + word_count + account_age +
        source_followers_count + source_friends_count + source_verified,
    family = "binomial",
    data = notes_ratings_source
)

notes_ratings_source <- notes_ratings_source %>%
    mutate(predicted_prob = predict(helpful_model, type = "response"))

predictors <- notes_ratings_source %>% select(word_count, account_age, source_followers_count, source_friends_count)
outcome <- notes_ratings_source$helpful


predictors_scaled <- as_tibble(scale(predictors))

notes_scaled <- bind_cols(
    predictors_scaled,
    classification = notes_ratings_source$classification,
    trustworthySources = notes_ratings_source$trustworthySources,
    source_verified = notes_ratings_source$source_verified,
    helpful = outcome
)

notes_scaled$classification <- relevel(factor(notes_scaled$classification), ref = "NOT_MISLEADING")
notes_scaled$trustworthySources <- as.factor(notes_scaled$trustworthySources)

helpful_model <- glm(helpful ~ classification + trustworthySources + word_count + account_age + source_followers_count + source_friends_count + source_verified,
    data = notes_scaled, family = "binomial"
)

coef <- tidy(helpful_model)
coef <- coef %>% filter(term != "(Intercept)")

coef$term <- factor(coef$term, levels = c(
    "classificationMISINFORMED_OR_POTENTIALLY_MISLEADING",
    "trustworthySourcesNo trustworthy",
    "word_count",
    "account_age",
    "source_followers_count",
    "source_friends_count",
    "source_verifiedTRUE"
))

ggplot(coef, aes(x = term, y = estimate)) +
    geom_point(size = 8, color = "sea green") +
    geom_errorbar(aes(ymin = estimate - (std.error * 2.56), ymax = estimate + (std.error * 2.56)), width = 0.2, color = "sea green") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 13)) +
    labs(x = NULL, y = NULL) +
    geom_vline(xintercept = c(2.5, 3.5), linetype = "dashed", color = "black") +
    annotate("text", x = 1, y = 0.95, label = "User categorization", size = 4, fontface = "bold") +
    annotate("text", x = 3, y = 0.95, label = "Text explanation", size = 4, fontface = "bold") +
    annotate("text", x = 4, y = 0.95, label = "Source tweet", size = 4, fontface = "bold") +
    scale_x_discrete(labels = c(
        "account_age" = "Account age",
        "classificationMISINFORMED_OR_POTENTIALLY_MISLEADING" = " Misleading",
        "source_followers_count" = "Followers",
        "source_friends_count" = "Followees",
        "source_verifiedTRUE" = "Verified",
        "trustworthySourcesNo trustworthy" = "Trustworthy Sources",
        "word_count" = "Word count"
    ))
```


#Fig 6c
```{r}
notes_with_ratings <- inner_join(notes, ratings, by = "noteId")
notes_ratings_source <- inner_join(notes_with_ratings, source_tweets, by = c("noteId", "tweetId"))

current_date <- Sys.Date()
current_year <- format(current_date, "%Y")

notes_ratings_source <- notes_ratings_source |> mutate(
    account_age = as.numeric(current_year) - as.numeric(year(notes_ratings_source$source_account_created_at))
)

ccdf_data <- notes_ratings_source %>%
    group_by(classification, account_age) %>%
    summarise(count = n()) %>%
    group_by(classification) %>%
    mutate(
        ccdf = rev(cumsum(rev(count))),
        total = sum(count),
        percent = (ccdf / total) * 100
    )

ggplot(ccdf_data, aes(x = account_age, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = scales::comma) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not misleading"
        )
    ) +
    labs(
        x = "Account age",
        y = "CCDF (%)",
        title = "(c) Account age"
    )
```

#Fig 6a
```{r}
ccdf_data <- notes_ratings_source %>%
    group_by(classification, source_followers_count) %>%
    summarise(count = n()) %>%
    group_by(classification) %>%
    mutate(
        ccdf = rev(cumsum(rev(count))),
        total = sum(count),
        percent = (ccdf / total) * 100
    )

ggplot(ccdf_data, aes(x = source_followers_count, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(
        breaks = c(100, 10, 1, 0.1, 0.01),
        labels = label_percent(scale = 1)
    ) +
    scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not misleading"
        )
    ) +
    labs(
        x = "Followers",
        y = "CCDF (%)",
        title = "(a) Followers"
    )
```

#Fig 6b
```{r}
ccdf_data <- notes_ratings_source %>%
    group_by(classification, source_friends_count)
View(ccdf_data) %>%
    summarise(count = n()) %>%
    group_by(classification) %>%
    mutate(
        ccdf = rev(cumsum(rev(count))),
        total = sum(count),
        percent = (ccdf / total) * 100
    )
View(ccdf_data)

ggplot(ccdf_data, aes(x = source_friends_count, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = percent) +
    scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not misleading"
        )
    ) +
    labs(
        x = "Followees",
        y = "CCDF (%)",
        title = "(b) Followees"
    )
```