
```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)
library(ggplot2)
library(stringr)
library(broom)
library(MASS)
```

```{r}
notes <- read_tsv("filtered_data/filtered_notes.tsv")
ratings <- read_tsv("filtered_data/complete_filtered_ratings.tsv")
```

#Figure 2
```{r}
notes$trustworthySources <- factor(notes$trustworthySources, levels = c(0, 1), labels = c("Trustworthy sources", "No trustworthy"))

ggplot(notes, aes(x = classification, fill = trustworthySources)) +
    geom_bar() +
    scale_x_discrete(labels = c(
        "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
        "NOT_MISLEADING" = "Not Misleading"
    )) +
    coord_flip()
```

#Figure 3
```{r graph}
misleading_counts <- notes %>%
    summarise(
        misleadingOther = sum(misleadingOther),
        misleadingOutdatedInformation = sum(misleadingOutdatedInformation),
        misleadingFactualError = sum(misleadingFactualError),
        misleadingManipulatedMedia = sum(misleadingManipulatedMedia),
        misleadingMissingImportantContext = sum(misleadingMissingImportantContext),
        misleadingUnverifiedClaimAsFact = sum(misleadingUnverifiedClaimAsFact),
        misleadingSatire = sum(misleadingSatire)
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

ggplot(misleading_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "red") +
    coord_flip() +
    scale_x_discrete(labels = c(
        "misleadingOther" = "Other",
        "misleadingOutdatedInformation" = "Outdated information",
        "misleadingFactualError" = "Factual error",
        "misleadingManipulatedMedia" = "Manipulated media",
        "misleadingMissingImportantContext" = "Missing importamt context",
        "misleadingUnverifiedClaimAsFact" = "Unverified claim as fact",
        "misleadingSatire" = "Satire"
    ))
```

#Figure 4.
```{r graph}
misleading_counts <- notes %>%
    summarise(
        notMisleadingPersonalOpinion = sum(notMisleadingPersonalOpinion),
        notMisleadingOther = sum(notMisleadingOther),
        notMisleadingClearlySatire = sum(notMisleadingClearlySatire),
        notMisleadingFactuallyCorrect = sum(notMisleadingFactuallyCorrect),
        notMisleadingOutdatedButNotWhenWritten = sum(notMisleadingOutdatedButNotWhenWritten),
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

ggplot(misleading_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "blue") +
    coord_flip() +
    labs(y = "Number of Birdwatches notes") +
    scale_x_discrete(labels = c(
        "notMisleadingOther" = "Other",
        "notMisleadingOutdatedButNotWhenWritten" = "Outdated but not when written",
        "notMisleadingPersonalOpinion" = "Personal opinion",
        "notMisleadingFactuallyCorrect" = "Factually correct",
        "notMisleadingClearlySatire" = "Clearly satire"
    ))
```

#Figure 5c.
```{r compute ccdf}
notes <- mutate(notes, word_count = str_count(summary, "\\w+"))

notes <- arrange(notes, word_count)
count_of_distinct <- group_by(notes, classification, word_count) |>
    summarize(count = n()) |>
    group_by(classification) |>
    arrange(classification, word_count) |>
    mutate(notes_with_count = rev(cumsum(rev(count))), total_notes = sum(count), percent = (notes_with_count / total_notes) * 100)

ggplot(count_of_distinct, aes(x = word_count, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = scales::comma) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not Misleading"
        )
    ) +
    labs(
        x = "Word count",
        y = "CCDF (%)",
        title = "CCDF of Word Count by Misleading Status",
        color = "Classification"
    )
```


#Figure 7a.
```{r compute ccdf}
ratings <- group_by(ratings, noteId) |> mutate(votecount = n())

notes$votecount <- ratings$votecount[match(notes$noteId, ratings$noteId)]
# we assumed NA = 0 bc it won't have any row from the ratings table
notes$votecount[is.na(notes$votecount)] <- 0
ratings <- group_by(ratings, noteId) |> mutate(helpful_ratio = sum(helpful) / votecount)

notes$helpful_ratio <- ratings$helpful_ratio[match(notes$noteId, ratings$noteId)]
# we assumed NA = 0 bc it won't have any row from the ratings table
notes$helpful_ratio[is.na(notes$helpful_ratio)] <- 0

helpful_ratio <- group_by(notes, classification, helpful_ratio) |>
    summarize(count = n()) |>
    group_by(classification) |>
    arrange(classification, helpful_ratio) |>
    mutate(helpful = rev(cumsum(rev(count))), total_notes = sum(count), percent = (helpful / total_notes) * 100)

ggplot(helpful_ratio, aes(x = helpful_ratio, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10() +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not Misleading"
        )
    ) +
    labs(
        x = "Helpful Ratios",
        y = "CCDF (%)",
        title = "Helpfulness ratio",
        color = "Classification"
    )
```


#Figure 7b.
```{r compute ccdf}
count_of_votes <- group_by(notes, classification, votecount) |>
    summarize(count = n()) |>
    group_by(classification) |>
    arrange(classification, votecount) |>
    mutate(votes = rev(cumsum(rev(count))), total_notes = sum(count), percent = (votes / total_notes) * 100)
ggplot(count_of_votes, aes(x = votecount, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = scales::comma) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not Misleading"
        )
    ) +
    labs(
        x = "Votes (helpful & not helpful)",
        y = "CCDF (%)",
        title = "Total Votes",
        color = "Classification"
    )
```


#Figure 8.

```{r}
ratings <- read_tsv("filtered_data/complete_filtered_ratings.tsv")

helpful_ratings_counts <- ratings %>%
    summarise(
        helpfulInformative = sum(helpfulInformative),
        helpfulClear = sum(helpfulClear),
        helpfulGoodSources = sum(helpfulGoodSources),
        helpfulEmpathetic = sum(helpfulEmpathetic),
        helpfulUniqueContext = sum(helpfulUniqueContext),
        helpfulAddressesClaim = sum(helpfulAddressesClaim),
        helpfulImportantContext = sum(helpfulImportantContext),
        helpfulOther = sum(helpfulOther)
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

ggplot(helpful_ratings_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "navyblue") +
    coord_flip() +
    scale_x_discrete(labels = c(
        "helpfulInformative" = "Informative",
        "helpfulClear" = "Clear",
        "helpfulGoodSources" = "Good sources",
        "helpfulEmpathetic" = "Emphatetic",
        "helpfulUniqueContext" = "Unique context",
        "helpfulAddressesClaim" = "Addresses claim",
        "helpfulImportantContext" = "Important context",
        "helpfulOther" = "Other"
    ))
```

#Figure 9
```{r}
unhelpful_ratings_counts <- ratings %>%
    summarise(
        notHelpfulSourcesMissingOrUnreliable = sum(notHelpfulSourcesMissingOrUnreliable),
        notHelpfulOpinionSpeculationOrBias = sum(notHelpfulOpinionSpeculationOrBias),
        notHelpfulMissingKeyPoints = sum(notHelpfulMissingKeyPoints),
        notHelpfulArgumentativeOrBiased = sum(notHelpfulArgumentativeOrBiased),
        notHelpfulIncorrect = sum(notHelpfulIncorrect),
        notHelpfulOffTopic = sum(notHelpfulOffTopic),
        notHelpfulHardToUnderstand = sum(notHelpfulHardToUnderstand),
        notHelpfulSpamHarassmentOrAbuse = sum(notHelpfulSpamHarassmentOrAbuse),
        notHelpfulOutdated = sum(notHelpfulOutdated),
        notHelpfulIrrelevantSources = sum(notHelpfulIrrelevantSources)
    ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))

ggplot(unhelpful_ratings_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "dark red") +
    coord_flip() +
    scale_x_discrete(labels = c(
        notHelpfulSourcesMissingOrUnreliable = ("Sources missing or unreliable"),
        notHelpfulOpinionSpeculationOrBias = ("Opinion speculation or bias"),
        notHelpfulMissingKeyPoints = ("Missing key points"),
        notHelpfulArgumentativeOrBiased = ("Argumentative or inflammatory"),
        notHelpfulIncorrect = ("Incorrect"),
        notHelpfulOffTopic = ("Off topic"),
        notHelpfulHardToUnderstand = ("Hard to understand"),
        notHelpfulSpamHarassmentOrAbuse = ("Spam harassment or abuse"),
        notHelpfulOutdated = ("Outdated"),
        notHelpfulIrrelevantSources = ("Irrevalent sources")
    ))
```

#Fig 6a
```{r}
notes_with_ratings <- inner_join(notes, ratings, by = "noteId")
notes_ratings_source <- inner_join(notes_with_ratings, source_tweets, by = c("noteId", "tweetId"))

current_date <- Sys.Date()
current_year <- format(current_date, "%Y")

notes_ratings_source <- notes_ratings_source |> mutate(
    account_age = as.numeric(current_year) - as.numeric(year(notes_ratings_source$source_account_created_at))
)
ccdf_data <- notes_ratings_source %>%
    group_by(classification, source_followers_count) %>%
    summarise(count = n()) %>%
    group_by(classification) %>%
    mutate(
        ccdf = rev(cumsum(rev(count))),
        total = sum(count),
        percent = (ccdf / total) * 100
    )

ggplot(ccdf_data, aes(x = source_followers_count, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(
        breaks = c(100, 10, 1, 0.1, 0.01),
        labels = label_percent(scale = 1)
    ) +
    scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not misleading"
        )
    ) +
    labs(
        x = "Followers",
        y = "CCDF (%)",
        title = "(a) Followers"
    )
```

#Fig 6b
```{r}
ccdf_data <- notes_ratings_source %>%
    group_by(classification, source_friends_count) %>%
    summarise(count = n()) %>%
    group_by(classification) %>%
    mutate(
        ccdf = rev(cumsum(rev(count))),
        total = sum(count),
        percent = (ccdf / total) * 100
    )

ggplot(ccdf_data, aes(x = source_friends_count, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = percent) +
    scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not misleading"
        )
    ) +
    labs(
        x = "Followees",
        y = "CCDF (%)",
        title = "(b) Followees"
    )
```


#Fig 6c
```{r}
ccdf_data <- notes_ratings_source %>%
    group_by(classification, account_age) %>%
    summarise(count = n()) %>%
    group_by(classification) %>%
    mutate(
        ccdf = rev(cumsum(rev(count))),
        total = sum(count),
        percent = (ccdf / total) * 100
    )

ggplot(ccdf_data, aes(x = account_age, y = percent, color = classification)) +
    geom_line(size = 1.2) +
    scale_y_log10(labels = scales::comma) +
    scale_color_manual(
        values = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "red",
            "NOT_MISLEADING" = "blue"
        ),
        labels = c(
            "MISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
            "NOT_MISLEADING" = "Not misleading"
        )
    ) +
    labs(
        x = "Account age",
        y = "CCDF (%)",
        title = "(c) Account age"
    )
```

```{bash}
# donwloaded file in browser bc didn't work to curl here (downloaded as empty)
load(file.path("C:/Users/ds3/Downloads/source_tweets.Rdata"), ournew_env <- new.env())
source_tweets <- ournew_env[["."]]
source_tweets |> head()
```

  
```{r}
# join data
notes_with_ratings <- inner_join(notes, ratings, by = c("noteId", "votecount"))
notes_ratings_source <- inner_join(notes_with_ratings, source_tweets, by = c("noteId", "tweetId"))

# reformat helpful
notes_ratings_source <- mutate(notes_ratings_source,
    helpful = if_else(!is.na(helpfulnessLevel) &
        helpfulnessLevel %in% c("HELPFUL", "SOMEWHAT_HELPFUL"), 1, helpful),
    notHelpful = if_else(!is.na(helpfulnessLevel) & helpfulnessLevel == "NOT_HELPFUL", 1, notHelpful)
)

# add account age
current_year <- as.numeric(format(Sys.Date(), "%Y"))
notes_ratings_source <- notes_ratings_source |>
    mutate(account_age = current_year - as.numeric(year(source_account_created_at)))

# filter to remove NA
notes_ratings_source <- notes_ratings_source %>%
    filter(
        !is.na(helpful),
        !is.na(classification),
        !is.na(trustworthySources),
        !is.na(word_count),
        !is.na(account_age),
        !is.na(source_followers_count),
        !is.na(source_friends_count),
        !is.na(source_verified)
    )

notes_ratings_source <- notes_ratings_source %>%
    mutate(source_followers_count = log(source_followers_count))

# get predictors that need to be scaled and outcome
predictors <- notes_ratings_source %>%
    select(word_count, account_age, source_followers_count, source_friends_count)
vote_predictors <- predictors

helpful_outcome <- notes_ratings_source$helpful
votecount_outcome <- notes_ratings_source$votecount

# get z-scores for predictors (standardize)
predictors_scaled <- as_tibble(scale(predictors))
vote_predictors_scaled <- as_tibble(scale(vote_predictors))

# combined the scaled predictors with the already categorical predictors
helpful_scaled <- bind_cols(
    predictors_scaled,
    classification = notes_ratings_source$classification,
    trustworthySources = notes_ratings_source$trustworthySources,
    source_verified = notes_ratings_source$source_verified,
    helpful = helpful_outcome
)

votes_scaled <- bind_cols(
    vote_predictors_scaled,
    classification = notes_ratings_source$classification,
    trustworthySources = notes_ratings_source$trustworthySources,
    source_verified = notes_ratings_source$source_verified,
    votecount = votecount_outcome
)

# set reference levels for categorical predictors
helpful_scaled$classification <- relevel(factor(helpful_scaled$classification), ref = "NOT_MISLEADING")
helpful_scaled$trustworthySources <- as.factor(helpful_scaled$trustworthySources)

votes_scaled$classification <- relevel(factor(votes_scaled$classification), ref = "NOT_MISLEADING")
votes_scaled$trustworthySources <- as.factor(votes_scaled$trustworthySources)

# fit models on standardized
helpful_model <- glm(
    helpful ~ classification + trustworthySources + word_count + account_age +
        source_followers_count + source_friends_count + source_verified,
    data = notes_scaled, family = "binomial"
)

votes_model <- glm.nb(
    votecount ~ classification + trustworthySources + word_count + account_age +
        source_followers_count + source_friends_count + source_verified,
    data = votes_scaled
)

# get model coefficients
votes_coef <- tidy(votes_model) |> filter(term != "(Intercept)")
coef <- tidy(helpful_model) %>% filter(term != "(Intercept)")

# set order to match figure
term_levels <- c(
    "classificationMISINFORMED_OR_POTENTIALLY_MISLEADING",
    "trustworthySourcesNo trustworthy",
    "word_count",
    "account_age",
    "source_followers_count",
    "source_friends_count",
    "source_verifiedTRUE"
)
votes_coef$term <- factor(votes_coef$term, levels = term_levels)
coef$term <- factor(coef$term, levels = term_levels)

# label models to differentiate
coef$Model <- "Helpfulness"
votes_coef$Model <- "Votecount"

# combine models and plot
combined_coef <- bind_rows(coef, votes_coef)

ggplot(combined_coef, aes(x = term, y = estimate, color = Model)) +
    geom_point(size = 6, position = position_dodge(width = 0.5)) +
    geom_errorbar(
        aes(ymin = estimate - std.error * 2.56, ymax = estimate + std.error * 2.56),
        width = 0.2, size = 1.2, position = position_dodge(width = 0.5)
    ) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12)) +
    labs(x = NULL, y = NULL, color = "Model") +
    geom_vline(xintercept = c(2.5, 3.5), linetype = "dashed", color = "black") +
    annotate("text", x = 1, y = max(combined_coef$estimate, na.rm = TRUE), label = "User categorization", size = 4, fontface = "bold") +
    annotate("text", x = 3, y = max(combined_coef$estimate, na.rm = TRUE), label = "Text explanation", size = 4, fontface = "bold") +
    annotate("text", x = 4, y = max(combined_coef$estimate, na.rm = TRUE), label = "Source tweet", size = 4, fontface = "bold") +
    scale_x_discrete(labels = c(
        "account_age" = "Account age",
        "classificationMISINFORMED_OR_POTENTIALLY_MISLEADING" = "Misleading",
        "source_followers_count" = "Followers",
        "source_friends_count" = "Followees",
        "source_verifiedTRUE" = "Verified",
        "trustworthySourcesNo trustworthy" = "Trustworthy Sources",
        "word_count" = "Word count"
    )) +
    scale_color_manual(values = c("Helpfulness" = "seagreen", "Votecount" = "orange"))
```
