```{r setup}
library(tidyverse)
library(knitr)
library(scales)

notes <- read_tsv("filtered_data/filtered_notes.tsv")


```

```{r graph}

num_cols <- select_if(notes, is.numeric)
num_cols <- num_cols |>
  select(-noteId, -createdAtMillis, -tweetId, -isMediaNote)
colCounts <- colSums(num_cols, na.rm = TRUE)
View(colCounts)

colCounts_df <- data.frame(
  category = names(colCounts),
  count = as.numeric(colCounts)
)


ggplot(colCounts_df, aes(x = category, y= count)) +  
  geom_bar(stat="identity") +
  coord_flip() 

  misleading_counts <- notes %>%
    summarise(
        misleadingOther = sum(misleadingOther),
        misleadingOutdatedInformation = sum(misleadingOutdatedInformation),
        misleadingFactualError= sum(misleadingFactualError),
        misleadingManipulatedMedia= sum(misleadingManipulatedMedia),
        misleadingMissingImportantContext= sum(misleadingMissingImportantContext),
        misleadingUnverifiedClaimAsFact= sum(misleadingUnverifiedClaimAsFact),
        misleadingSatire= sum(misleadingSatire)
        ) %>%
    pivot_longer(everything(), names_to = "tag", values_to = "count") %>%
    arrange(desc(count))
 
View(misleading_counts)
 
 
ggplot(misleading_counts, aes(x = reorder(tag, count), y = count)) +
    geom_bar(stat = "identity", fill = "red") +
    coord_flip() +
    labs(y = "Number of Birdwatches notes"
    ) +
    scale_x_discrete(labels = c(
    "misleadingOther" = "Other", 
    "misleadingOutdatedInformation" = "Outdated Information",
    "misleadingFactualError" = "Factual error",
    "misleadingManipulatedMedia" = "Manipulated media",
      "misleadingMissingImportantContext" = "Missing important context",
        "misleadingUnverifiedClaimAsFact" = "Unverified claim as fact",
        "misleadingSatire" = "Satire"
    
  ))     

```